=== ManuelTejeira/simoc/ACE/json/archive/macro_schema.json
{
	"$schema": "http://json-schema.org/schema#",
	"title" : "Habitat",
	"type" : "object",
	"id" : "habitat",
	"properties" : {
		"starting_resources" : {
			"type" : "object",
			"title" : "Starting Resources",
			"properties" : {
				"o2" : {
					"type" : "number"			
				},
				"co2" : {
					"type" : "number"
				},
				"nitrogen" : {
					"type" : "number"			
				},
				"argon" : {
					"type" : "number"
				},
				"water" : {
					"type" : "number"			
				},
				"waste_water" : {
					"type" : "number"
				}
			}
			

		},
		"power" : {
			"type" : "object",
			"title" : "Power",
			"properties" : {
				"solar_arrays" : {
					"type" : "integer"				
				},
				"battery_capacity" : {
					"type" : "number"
				},
				"stored_power" : {
					"type" : "number"
				}
			}
		},
		"structures" : {
			"type" : "array",
			"format" : "table",
			"title" : "Structures",
			"uniqueItems" : false,
			"items" : {
				"type" : "object",
				"properties" : {
					"type" : {
						"type" : "string",
						"enum" : [
							"greenhouse",
							"kitchen",
							"rec center",
							"clinic",
							"crew quarters",
							"storage facility",
							"lab",
							"bathroom",
							"shuttle bay",
							"rocket pad",
							"dining hall",
							"laundry",
							"classroom",
							"light rail",
							"sanctuary",
							"theatre",
							"workshop",
							"airlock",
							"rover dock"
						],
						"default" : "crew quarters"
					},
					"square_meters" : {
						"type" : "number"
					}
				}
			}
		},
		"starting_plants" : {
			"type" : "array",
			"format" : "table",
			"title" : "Starting Plants",
			"uniqueItems" : true,
			"items" : {
				"type" : "object",
				"properties" : {
					"type" : {
						"type" : "string",
						"enum" : [
							"cabbage",
							"carrot",
							"chard",
							"celery",
							"dry_bean",
							"green_onion",
							"lettuce",
							"pea", 
							"peanut", 
							"pepper",
							"radish",
							"red_beet",
							"rice",
							"snap_bean",
							"soybean",
							"spinach",
							"strawberry",
							"sweet_potato",
							"tomato",
							"wheat",
							"white_potato",
							"default_plant"
						],
						"default" : "default_plant"
					},
					"square_meters" : {
						"type" : "number"
					}
				}
			}
		},
		"habitants" : {
			"type" : "array",
			"format" : "table",
			"title" : "Habitants",
			"uniqueItems" : true,
			"items" : {
				"type" : "object",
				"properties" : {
					"type" : {
						"type" : "string",
						"enum" : [
							"human",
							"drone"
						],
						"default" : "human"
					},
					"quantity" : {
						"type" : "integer"
					}
				}
			}
		}
	}

}

=== ManuelTejeira/simoc/ACE/json/archive/macro_starting.json
{
          "starting_resources" : { "o2" : 10 , "co2" : 10, "nitrogen" : 10, "water" : 10000},
          "power" : {"battery_capacity" : 10000, "stored_power" : 5000},
          "structures" : [
            {
              "type" : "greenhouse",
              "square_meters" : 450
            },
            {
              "type" : "crew quarters",
              "square_meters" : 225
            },
            {
              "type" : "kitchen",
              "square_meters" : 100
            }
          ],
          "starting_plants" : [
            {
              "type" : "wheat",
              "square_meters" : 100
            },
            {
              "type" : "spinach",
              "square_meters" : 100
            },
            {
              "type" : "radish",
              "square_meters" : 100
            },
            {
              "type" : "chard",
              "square_meters" : 50
            }
          ],
          "habitants" : [
            {
              "type" : "human",
              "quantity" : 5
            },
            {
              "type" : "drone",
              "quantity" : 1
            }
          ]
        }
